---
# Install Neovim from source

- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
      - build-essential
    state: present
    update_cache: true
  become: true

- name: Clone Neovim repository
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim
    dest: /home/{{ ansible_user_id }}/neovim
    version: master

- name: Build Neovim
  ansible.builtin.shell: |
    cd /home/{{ ansible_user_id }}/neovim &&
    make CMAKE_BUILD_TYPE=RelWithDebInfo
  args:
    chdir: /home/{{ ansible_user_id }}/neovim
  # Lint
  register: neovim_build_result
  changed_when:
    neovim_build_result.rc != 0
    # creates: /usr/local/bin/nvim

- name: Install Neovim
  ansible.builtin.shell: |
    # cd build && cpack -G DEB && sudo dpkg -i nvim-linux-x86_64.deb
    cd build && cpack -G DEB && sudo dpkg -i nvim-linux-x86_64.deb
  become: true
  args:
    chdir: /home/{{ ansible_user_id }}/neovim
  # Lint
  register: neovim_install_result
  changed_when:
    neovim_install_result.rc != 0
    # creates: /usr/local/bin/nvim
